### ISSUE TITLE
missing part of code in scripts/run_DQ_Lore

### ISSUE THREAD

**Issue by Yukang-Lin** [AI4fun/DQ-LoRe#1]
Hi, it seems like in the script scripts/run_DQ_Lore, the ice selection code using trained_retriever is missing, so in qa_inference.py, metadata has an empty ice_prompts_list, could you please modify that, thanks!

**Comment by UGUESS-lzx** [comment]
I'm sorry that this is our oversight. Thank you very much for pointing it out！Now the sh file has been modified. If you have any other questions, please feel free to contact us!
